post_onboarding: {
  completed_steps: POST_ONBOARDING_STEP_TYPE_MANAGER_WELCOME
  completed_steps: POST_ONBOARDING_STEP_TYPE_USAGE_MODE
  completed_steps: POST_ONBOARDING_STEP_TYPE_AGENT_CONFIGURATION
  completed_steps: POST_ONBOARDING_STEP_TYPE_ADD_WORKSPACE
}
agent_onboarding_completed: AGENT_ONBOARDING_STATE_COMPLETED
migrate_convos_into_projects: MIGRATION_STATUS_COMPLETED
installation_uuid: "805b8b43-1242-4f96-bcc2-d24f2a70002f"
migrate_retroactive_projects: RETROACTIVE_MIGRATION_STATUS_COMPLETED_UNNECESSARY
migrations: {
  key: 2
  value: MIGRATION_STATUS_COMPLETED
}
migrations: {
  key: 3
  value: MIGRATION_STATUS_COMPLETED
}
migrations: {
  key: 4
  value: MIGRATION_STATUS_COMPLETED
}
